# .cargo/config.toml
[build]
target = "bpfel-unknown-none"

[target.bpfel-unknown-none]
rustflags = ["-Ctarget-cpu=generic"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
